        <table class="table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Actualizar</th>
                    <th>Eliminar</th>
                </tr>
            </thead>
            <tbody>
                <?php
                    foreach ($categories as $category) {
                        echo "<tr>";
                        echo "<form method='post' action='categorias/editar/{$category->categoria_id}'>";
                        echo "<td> {$category->categoria_id} </td>";
                        echo "<td><input class='form-control' type='text' name='category_name' value='{$category->categoria_nombre}'></td>";
                        echo "<td><input type='submit' class='btn btn-info' value='Actualizar'></td>";
                        echo "</form>";
                        echo "<td><form method='post' action='categorias/borrar/{$category->categoria_id}'><input type='submit' class='btn btn-dark' value='Borrar'></input></form></td>";
                        echo "</tr>";
                    }
                ?>
                <tr>
                    <form action="categorias/crear" method="post">
                        <td><label for="category_id"> # </label></td>
                        <td><input placeholder='Ingrese nueva categoría' class='form-control' type="text" name="category_name" id="category_name" required></td>
                        <td><button class="btn btn-success" type="submit">Agregar</button></td>
                    </form>
                </tr>
            </tbody>
        </table>
