<?php require './templates/header.phtml' ?>
<div class="accordion accordion-flush" id="accordionFlushExample">

<!-- Administrador Productos -->

  <div class="accordion-item">
    <h1 class="accordion-header">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">
        Administrador Productos
      </button>
    </h1>
    <div id="flush-collapseTwo" class="accordion-collapse collapse show" data-bs-parent="#accordionFlushExample">
      <div class="accordion-body">
        <?php require './templates/admin-productos.phtml' ?>
      </div>
    </div>
  </div>

  <!-- Administrador Categorias -->

  <div class="accordion-item">
    <h1 class="accordion-header">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
        Administrador Categorias
      </button>
    </h1>
    <div id="flush-collapseOne" class="accordion-collapse collapse" data-bs-parent="#accordionFlushExample">
      <div class="accordion-body col-md-8">
        <?php require './templates/admin-categorias.phtml' ?>
      </div>
    </div>
  </div>

</div>
<?php require './templates/footer.phtml' ?>

