<?php require 'templates/header.phtml' ?>

<section class="categories">
    <h2 class="text-center my-5">Categorias</h2>
    <div class="container">
        <div class="row">
            <?php $count = 0; ?>
            <?php foreach ($category as $category) : ?>
                <div class="col-4">
                    <div class="card">
                        <img src="https://picsum.photos/500/300" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title"><?= $category->categoria_nombre ?></h5>
                            <a href="productos/<?= $category->categoria_id ?>" class="btn btn-primary text-center">Ver más</a>
                        </div>
                    </div>
                </div>
                <?php $count++; ?>
                <?php if ($count % 3 == 0) : ?>
                    </div><div class="row">
                <?php endif; ?>
            <?php endforeach ?>
        </div>
    </div>
</section>

<?php require 'templates/footer.phtml' ?>