<?php require 'templates/header.phtml' ?>

<div class="mt-5 w-25 mx-auto">
    <form method="POST" action="login">
        <div class="form-group">
        <label for="InputUsername" class="form-label">Usuario</label>
            <input type="text" required class="form-control" name="username" aria-describedby="emailHelp">
        </div>
        <div class="form-group">
            <label for="InputPassword" class="form-label">Contraseña</label>
            <input type="password" required class="form-control" name="password">
        </div>
        <button type="submit" class="btn btn-primary mt-3">Entrar</button>
    </form>
</div>

<?php require 'templates/footer.phtml' ?>